
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dinam
 */public class confirmReservation extends javax.swing.JFrame {
// Constructor receives data from the Search screen
      private String finalStartDate;
    private String finalEndDate;
    public confirmReservation(){
        
    }
    public confirmReservation(String carModel, String fuel, String price, String period, String start, String end) {
        initComponents();
         this.setLocationRelativeTo(null);
        // Store dates in global variables for later use in proceedPaym
        this.finalStartDate = start;
        this.finalEndDate = end;

        // Fill UI fields
        vechicleField.setText(carModel);
        fuelField.setText(fuel);
        dailRateField.setText(price);
        periodField.setText(period); 

        // Calculate Total Cost 
        try {
            double dailyPrice = Double.parseDouble(price);
            int days = Integer.parseInt(period);
            double total = dailyPrice * days;
            totalCostField.setText(total + " EGP");
        } catch (Exception e) {
            totalCostField.setText("0.0");
        }

        // Make fields read-only
        vechicleField.setEditable(false);
        fuelField.setEditable(false);
        dailRateField.setEditable(false);
        periodField.setEditable(false);
        totalCostField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmRes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        vehicle = new javax.swing.JLabel();
        fuelTypeCnfrm = new javax.swing.JLabel();
        dailyRateCnfrm = new javax.swing.JLabel();
        periodCnfrm = new javax.swing.JLabel();
        vechicleField = new javax.swing.JTextField();
        fuelField = new javax.swing.JTextField();
        dailRateField = new javax.swing.JTextField();
        periodField = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        totalCostField = new javax.swing.JTextField();
        customerName = new javax.swing.JLabel();
        TotalCost = new javax.swing.JLabel();
        customerField = new javax.swing.JTextField();
        proceedPaym = new javax.swing.JButton();
        cancell = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Clear");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        confirmRes.setBackground(new java.awt.Color(255, 102, 0));
        confirmRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmRes.setForeground(new java.awt.Color(0, 0, 204));
        confirmRes.setText("Confirm Reservation");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        vehicle.setText("Vehicle");

        fuelTypeCnfrm.setText("Fuel Type");

        dailyRateCnfrm.setText("Daily Rate");

        periodCnfrm.setText("Period");

        vechicleField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vechicleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vechicleFieldActionPerformed(evt);
            }
        });

        fuelField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fuelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelFieldActionPerformed(evt);
            }
        });

        dailRateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dailRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailRateFieldActionPerformed(evt);
            }
        });

        periodField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        periodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodFieldActionPerformed(evt);
            }
        });

        status.setText("Status");

        statusField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodCnfrm, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyRateCnfrm)
                    .addComponent(fuelTypeCnfrm, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dailRateField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(fuelField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vechicleField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(periodField)
                    .addComponent(statusField))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicle)
                    .addComponent(vechicleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelTypeCnfrm)
                    .addComponent(fuelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dailyRateCnfrm)
                    .addComponent(dailRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(periodCnfrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(status)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalCostField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCostFieldActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerName.setText("Customer Name");

        TotalCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalCost.setForeground(new java.awt.Color(0, 0, 204));
        TotalCost.setText("Total Cost");

        customerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFieldActionPerformed(evt);
            }
        });

        proceedPaym.setBackground(new java.awt.Color(0, 153, 51));
        proceedPaym.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proceedPaym.setForeground(new java.awt.Color(255, 255, 255));
        proceedPaym.setText("Proceed to Payment");
        proceedPaym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedPaymActionPerformed(evt);
            }
        });

        cancell.setBackground(new java.awt.Color(204, 0, 0));
        cancell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancell.setForeground(new java.awt.Color(255, 255, 255));
        cancell.setText("Cancel Reservation");
        cancell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmRes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(proceedPaym, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancell))
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customerName))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(confirmRes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedPaym)
                    .addComponent(cancell))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vechicleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vechicleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vechicleFieldActionPerformed

    private void fuelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelFieldActionPerformed

    private void dailRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailRateFieldActionPerformed

    private void periodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodFieldActionPerformed

    private void totalCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCostFieldActionPerformed

    private void customerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerFieldActionPerformed

    private void proceedPaymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedPaymActionPerformed

    if (customerField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter customer Name!");
        return;
    }

    customerController controller = new customerController();
    
    
    String cleanPrice = totalCostField.getText().replace("EGP", "").trim();
    double total = Double.parseDouble(cleanPrice);

   
    boolean success = controller.makeReservation(
        customerField.getText(), 
        this.finalStartDate, 
        this.finalEndDate,        
        total,
        statusField.getText()
    );

    if (success) {
        JOptionPane.showMessageDialog(null, "Reservation Saved Successfully! Opening Payment...");
        
    
        Reservation res = new Reservation();
        res.setTotalCost(total);
        res.setReservationId(customerField.getText()); 
        
        PaymentUI paymentScreen = new PaymentUI(res); 
        paymentScreen.setVisible(true);

        this.dispose(); // إ
        
    } else {
        JOptionPane.showMessageDialog(null, "Error: Could not save to Database.");
    }
    }//GEN-LAST:event_proceedPaymActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void cancellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellActionPerformed
     // Display a confirmation dialog before canceling
    int response = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to cancel this reservation?", 
            "Confirm Cancellation", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        // Return to the main search screen and close this window
        // new ReservationGUI().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_cancellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 new confirmReservation(
                "Toyota Camry 2024", 
                "Gasoline", 
                "500.0", 
                "5", 
                "2026-05-01", 
                "2026-05-06"
            ).setVisible(true);
        }
              
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalCost;
    private javax.swing.JButton cancell;
    private javax.swing.JLabel confirmRes;
    private javax.swing.JTextField customerField;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField dailRateField;
    private javax.swing.JLabel dailyRateCnfrm;
    private javax.swing.JTextField fuelField;
    private javax.swing.JLabel fuelTypeCnfrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel periodCnfrm;
    private javax.swing.JTextField periodField;
    private javax.swing.JButton proceedPaym;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField totalCostField;
    private javax.swing.JTextField vechicleField;
    private javax.swing.JLabel vehicle;
    // End of variables declaration//GEN-END:variables
}