/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author daliaelbarbary
 */
public class PaymentUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentUI.class.getName());

    private final TransactionController controller = new TransactionController();
    private final Payment currentPayment = new Payment();
    private Reservation currentReservation;
    private String systemGeneratedCode;
private double amount;
    /**
     * Creates new form PaymentUI
     */
    public PaymentUI(Reservation res) {
        initComponents();
        this.setLocationRelativeTo(null);
        showVerificationSection(false);
       
        this.currentReservation = res;
        
        if (res != null) {
            this.amount = res.getTotalCost();
            txtAmount.setText(String.valueOf(this.amount));
        }
    }


    private void showVerificationSection(boolean visible) {
        lblVarificationCode.setVisible(visible);
        txtauthCode.setVisible(visible);
        btnverifyCode.setVisible(visible);
        jSeparator4.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVarificationCode = new javax.swing.JLabel();
        txtauthCode = new javax.swing.JTextField();
        btnverifyCode = new javax.swing.JButton();
        btnPayNow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPaymentTitle = new javax.swing.JLabel();
        lblCardDetailsTitle = new javax.swing.JLabel();
        txtExpiry = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        txtCardNumber = new javax.swing.JTextField();
        lblCurrency = new javax.swing.JLabel();
        ComboBoxCurrency = new javax.swing.JComboBox<>();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVarificationCode.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblVarificationCode.setText("Varification Code :");

        txtauthCode.setText("Auth Code");
        txtauthCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtauthCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtauthCodeFocusLost(evt);
            }
        });
        txtauthCode.addActionListener(this::txtauthCodeActionPerformed);

        btnverifyCode.setBackground(new java.awt.Color(16, 185, 129));
        btnverifyCode.setForeground(new java.awt.Color(255, 255, 255));
        btnverifyCode.setText("Confirm");
        btnverifyCode.addActionListener(this::btnverifyCodeActionPerformed);

        btnPayNow.setBackground(new java.awt.Color(37, 99, 235));
        btnPayNow.setForeground(new java.awt.Color(255, 255, 255));
        btnPayNow.setText("Pay Now");
        btnPayNow.setPreferredSize(new java.awt.Dimension(72, 23));
        btnPayNow.addActionListener(this::btnPayNowActionPerformed);

        btnCancel.setBackground(new java.awt.Color(107, 114, 128));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        lblPaymentTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        lblPaymentTitle.setText("Process Secure Payment");
        lblPaymentTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        lblCardDetailsTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblCardDetailsTitle.setText("Card Details");

        txtExpiry.setText("MM/YY");
        txtExpiry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtExpiryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpiryFocusLost(evt);
            }
        });

        txtCVV.setText("CVV");
        txtCVV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCVVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCVVFocusLost(evt);
            }
        });

        txtCardNumber.setText("Card Number");
        txtCardNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCardNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCardNumberFocusLost(evt);
            }
        });

        lblCurrency.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCurrency.setText("Currency Convert : ");

        ComboBoxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EGP", "USD", "EUR" }));
        ComboBoxCurrency.addActionListener(this::ComboBoxCurrencyActionPerformed);

        lblAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAmount.setText("Total Cost :");

        txtAmount.setEditable(false);
        txtAmount.setText("0.0");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVarificationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtauthCode, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtCardNumber)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAmount)
                                        .addComponent(lblCurrency)
                                        .addComponent(lblCardDetailsTitle))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ComboBoxCurrency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnverifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblPaymentTitle)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPaymentTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrency)
                    .addComponent(ComboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblCardDetailsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtauthCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVarificationCode))
                .addGap(30, 30, 30)
                .addComponent(btnverifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtauthCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthCodeActionPerformed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed

        // Capture user input from text fields
        String card = txtCardNumber.getText();
        String cvv = txtCVV.getText();
        String expiry = txtExpiry.getText();

        // Call the controller to validate data and get status message
        String validationResult = controller.validateResponse(card, cvv, expiry);

        if (validationResult.equals("SUCCESS")) {
            // Proceed with verification code generation
            this.systemGeneratedCode = controller.requestVerificationCode(currentPayment);

            // Update UI components
            showVerificationSection(true);
            btnPayNow.setEnabled(false);

            // Show success alert to user
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Validation Successful!\nYour Verification Code is: " + systemGeneratedCode);
        } else {
            // Show the specific error returned by the controller
            javax.swing.JOptionPane.showMessageDialog(this,
                    validationResult,
                    "Validation Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPayNowActionPerformed

    private void btnverifyCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyCodeActionPerformed
       
        

        
        String userInput = txtauthCode.getText();
        currentPayment.setAuthCode(userInput);
    String result = controller.verifyCode(userInput, systemGeneratedCode, currentReservation, currentPayment);

    switch (result) {
        case "SUCCESS" -> {
            javax.swing.JOptionPane.showMessageDialog(this, "Payment Successful! Record saved.");
            this.dispose();
        }
        case "CANCELLED" -> {
            // This message confirms to the user that the failure was logged
            javax.swing.JOptionPane.showMessageDialog(this, "Too many attempts. Transaction recorded as Cancelled.");
            this.dispose();
        }
        default -> {
           // Show remaining attempts
           int remaining = 3 - controller.getVerificationAttempts();
           javax.swing.JOptionPane.showMessageDialog(this, 
           "Wrong Code! You have " + remaining + " attempts left.");
        }
    }
         

    }//GEN-LAST:event_btnverifyCodeActionPerformed

    private void ComboBoxCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCurrencyActionPerformed
        //Check if we actually have a reservation to calculate prices for
        if (currentReservation != null) {

            //Get the selected currency from the ComboBox (EGP, USD, etc.)
            String selectedCurrency = (String) ComboBoxCurrency.getSelectedItem();

            // Ask the controller to calculate the converted amount
             double convertedAmount = controller.processTransaction(currentReservation, currentPayment, selectedCurrency);

            //Update the text field with 2 decimal places (e.g., 100.50)
            txtAmount.setText(String.format("%.2f", convertedAmount));

        } else {
            // Optional: If no reservation is loaded, keep it at 0.0
            txtAmount.setText("0.0");
        }
    }//GEN-LAST:event_ComboBoxCurrencyActionPerformed

    private void txtCardNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardNumberFocusGained
        if (txtCardNumber.getText().equals("Card Number")) {
            txtCardNumber.setText("");
        }
    }//GEN-LAST:event_txtCardNumberFocusGained

    private void txtCardNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardNumberFocusLost
        if (txtCardNumber.getText().isEmpty()) {
            txtCardNumber.setText("Card Number");
        }
    }//GEN-LAST:event_txtCardNumberFocusLost

    private void txtCVVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCVVFocusGained
        if (txtCVV.getText().equals("CVV")) {
            txtCVV.setText("");
        }
    }//GEN-LAST:event_txtCVVFocusGained

    private void txtCVVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCVVFocusLost
        if (txtCVV.getText().isEmpty()) {
            txtCVV.setText("CVV");

        }
    }//GEN-LAST:event_txtCVVFocusLost

    private void txtExpiryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpiryFocusGained
        if (txtExpiry.getText().equals("MM/YY")) {
            txtExpiry.setText("");

        }
    }//GEN-LAST:event_txtExpiryFocusGained

    private void txtExpiryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpiryFocusLost
        if (txtExpiry.getText().isEmpty()) {
            txtExpiry.setText("MM/YY");

        }
    }//GEN-LAST:event_txtExpiryFocusLost

    private void txtauthCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthCodeFocusGained
        if (txtauthCode.getText().equals("Auth Code")) {
            txtauthCode.setText("");

        }
    }//GEN-LAST:event_txtauthCodeFocusGained

    private void txtauthCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthCodeFocusLost
        if (txtauthCode.getText().isEmpty()) {
            txtauthCode.setText("Auth Code");
            txtauthCode.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtauthCodeFocusLost

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
        // Create an instance of the previous screen
        confirmReservation previousScreen = new confirmReservation();

        // Make the previous screen visible
        previousScreen.setVisible(true);

        // Center the previous screen (optional but better)
        previousScreen.setLocationRelativeTo(null);

        // Close (Dispose) the current PaymentUI screen
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           Reservation testRes = new Reservation(); 
        testRes.setTotalCost(0.0);
        
        new PaymentUI(testRes).setVisible(true);

          

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCurrency;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JButton btnverifyCode;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCardDetailsTitle;
    private javax.swing.JLabel lblCurrency;
    private javax.swing.JLabel lblPaymentTitle;
    private javax.swing.JLabel lblVarificationCode;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtExpiry;
    private javax.swing.JTextField txtauthCode;
    // End of variables declaration//GEN-END:variables
}
